app/controllers/auth_controller.py
from flask import Blueprint, current_app, render_template, request, flash, redirect, url_for, session
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
from app.model.models import User
from app.View.forms import RegisterForm, LoginForm, ForgetPasswordForm, ChangePasswordForm, EditProfileForm
from app import db, mail
from flask_mail import Message

# Define the auth Blueprint for handling authentication-related routes
auth = Blueprint('auth', __name__)

# Route for user registration
@auth.route("/register", methods=['GET', 'POST'])
def register():
    """
    Route for user registration.
    """
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        # Check if user with the provided email or UWA ID already exists
        existing_user = User.query.filter(
            (User.email == form.email.data) | (User.uwa_id == form.uwa_id.data)
        ).first()
        if existing_user is None:
            # Create a new user
            new_user = User(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                uwa_id=form.uwa_id.data,
                email=form.email.data,
                major=form.major.data,
                is_disabled=False,
                timestamp=datetime.utcnow(),
                role='user'
            )
            new_user.set_password(form.password.data)
            try:
                # Add the new user to the database
                db.session.add(new_user)
                db.session.commit()
                flash('Registration successful! You can now login.', 'success')
                return redirect(url_for('auth.login'))
            except Exception as e:
                # Rollback in case of any error during the database transaction
                db.session.rollback()
                flash(f"Failed to register the user due to {e}", "error")
        else:
            flash('Email or UWA ID already exists.', 'error')
    return render_template("auth/register.html", form=form)

# Route for user login
@auth.route('/login', methods=['GET', 'POST'])
def login():
    """
    Route for user login.
    """
    form = LoginForm()
    if form.validate_on_submit():
        # Check if the user exists and the password is correct
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember_me.data)
            session['logged_in'] = True
            session['user_name'] = f"{user.first_name} {user.last_name}"
            session['user_id'] = user.id
            session['server_start_token'] = current_app.config['SERVER_START_TOKEN']
            return redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check your email and password.', 'danger')
    return render_template('auth/login.html', form=form)

# Route for user logout
@auth.route('/logout')
def logout():
    """
    Route for user logout.
    """
    session.clear()
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))

# Route for forgetting password and resetting it
@auth.route('/forget_password', methods=['GET', 'POST'])
def forget_password():
    """
    Route for forgetting password and resetting it.
    """
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        # Fetch the user based on UWA ID and Email for extra verification
        user = User.query.filter_by(uwa_id=form.uwa_id.data, email=form.email.data).first()
        if user and user.first_name == form.first_name.data:
            # Update the user's password
            user.password_hash = generate_password_hash(form.new_password.data)
            db.session.commit()
            send_password_change_email(user)
            flash('Your password has been updated. Please check your email for confirmation.', 'success')
            return redirect(url_for('auth.login'))
        else:
            flash('Invalid credentials. Please try again.', 'danger')
    return render_template('auth/forgetpassword.html', form=form)

# Function to send password change confirmation email
def send_password_change_email(user):
    """
    Function to send password change confirmation email.
    """
    msg = Message('Password Change Confirmation', sender='cssedevconnect@gmail.com', recipients=[user.email])
    msg.body = f'''Hello {user.first_name},

This is a confirmation that the password for your account {user.email} has just been changed.

If you did not make this change, please contact support immediately.

Best regards,
CSSE DevConnect
'''
    mail.send(msg)

# Route for changing password
@auth.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    """
    Route to change the user's password.
    """
    form = ChangePasswordForm()
    if form.validate_on_submit():
        user = User.query.get_or_404(current_user.id)
        if user.check_password(form.old_password.data):
            user.set_password(form.new_password.data)
            db.session.commit()
            flash('Your password has been updated.', 'success')
            return redirect(url_for('auth.change_password'))
        else:
            flash('Old password is incorrect.', 'danger')
    return render_template('auth/change_password.html', form=form)

# Route for viewing and editing user profile
@auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Route for viewing and editing user profile.
    """
    user = User.query.get_or_404(current_user.id)
    form = EditProfileForm(obj=user)

    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.major = form.major.data
        db.session.commit()

        # Update session data to reflect changes
        session['user_name'] = f"{user.first_name} {user.last_name}"
        flash('Your profile has been updated.', 'success')
        return redirect(url_for('auth.profile'))

    return render_template('auth/profile.html', form=form)

# Route for accessing a secret page, available only to authenticated users
@auth.route('/secret')
@login_required
def secret():
    """
    Route for accessing a secret page, available only to authenticated users.
    """
    return 'Only authenticated users are allowed!'

app/controllers/main_controller.py
from flask import Blueprint, render_template, session, flash, redirect, url_for, request, Response, jsonify, json, g
from flask_mail import Message
from app import mail, db
import datetime
from flask_login import current_user, login_required
from app.View.forms import PostForm, FilterSortForm, ReplyForm
from app.model.models import Posts, Tag, User, Reply, FavoritePost
from sqlalchemy import func

# Define a Blueprint named 'main' for organizing routes and views
main = Blueprint('main', __name__)

# Index route
@main.route("/")
@main.route("/index")
@main.route("/home")
def index():
    """
    Index route. Redirects to posts page if user is authenticated, otherwise renders index page.
    """
    if current_user.is_authenticated:
        print("User is authenticated")
        return redirect(url_for('main.posts'))
    else:
        login_status = session.get('logged_in', False)
        return render_template("index.html", login=login_status)

# Mail check route
@main.route("/mailcheck")
def mailcheck():
    """
    Route to send a test email.
    """
    mail_check()
    return render_template("index.html", login=False)

def mail_check():
    """
    Function to send a test email.
    """
    ct = datetime.datetime.now()
    msg = Message("Hello from Flask", sender="cssedevconnect@gmail.com", recipients=["ramandatta87@gmail.com"])
    msg.body = f"This is a test email sent from Flask using Gmail. Mail Generated Time : {ct}"
    mail.send(msg)

# Route to add a new post
@main.route("/add_post", methods=['GET', 'POST'])
@login_required
def add_post():
    """
    Route to add a new post.
    """
    form = PostForm()
    if form.validate_on_submit():
        tag_text = form.tag.data.strip()
        tag = Tag.query.filter_by(tag=tag_text).first()
        if not tag:
            tag = Tag(tag=tag_text)
            db.session.add(tag)
            db.session.commit()

        career_preparation_value = 1 if form.question_type.data == 'career' else 0
        is_draft = form.draft.data

        post = Posts(
            title=form.title.data,
            content=form.content.data,
            tag_id=tag.id,
            career_preparation=career_preparation_value,
            author_id=current_user.id,
            deleted=False,
            answered=False,
            is_draft=is_draft
        )
        db.session.add(post)
        db.session.commit()

        if is_draft:
            flash("Blog Post Saved as Draft")
            return redirect(url_for('main.add_post'))
        else:
            flash("Blog Post Submitted Successfully")
            return redirect(url_for('main.view_post', post_id=post.id, origin='posts'))

    return render_template("/main/add_post.html", form=form)

# API endpoint for tag autocomplete
@main.route('/autocomplete', methods=['GET'])
def autocomplete():
    """
    API endpoint for tag autocomplete.
    """
    search = request.args.get('term')
    results = db.session.query(Tag.tag).filter(Tag.tag.like(f'%{search}%')).all()
    results = [result[0] for result in results]
    return Response(json.dumps(results), mimetype='application/json')

# API endpoint to fetch posts based on filters and sorting
@main.route('/api/posts')
def api_posts():
    """
    API endpoint to fetch posts based on filters and sorting.
    """
    page = request.args.get('page', 1, type=int)
    order = request.args.get('order', 'desc')
    posts_query = Posts.query.filter_by(is_draft=False).order_by(Posts.date_posted.asc() if order == 'asc' else Posts.date_posted.desc())
    pagination = posts_query.paginate(page=page, per_page=10, error_out=False)
    posts = pagination.items
    posts_data = []
    for post in posts:
        post_data = {
            'id': post.id,
            'title': post.title,
            'content': post.content,
            'author_first_name': post.author.first_name,
            'author_last_name': post.author.last_name,
            'tag': post.tag.tag if post.tag else 'N/A',
            'date_posted': post.date_posted.strftime('%B %d, %Y'),
            'answered': post.answered,
            'career_preparation': post.career_preparation
        }
        posts_data.append(post_data)
    return jsonify(posts_data=posts_data, has_next=pagination.has_next)

# API endpoint for post autocomplete
@main.route('/api/autocomplete_posts', methods=['GET'])
def autocomplete_posts():
    """
    API endpoint for post autocomplete.
    """
    search = request.args.get('q')
    filter_by = request.args.get('filter_by', 'author')

    if not search:
        return jsonify([])

    if filter_by == 'author':
        users = User.query.filter((User.first_name.ilike(f'%{search}%')) | (User.last_name.ilike(f'%{search}%'))).all()
        suggestions = [f'{user.first_name} {user.last_name}' for user in users]
    elif filter_by == 'title':
        posts = Posts.query.filter(Posts.title.ilike(f'%{search}%')).all()
        suggestions = [post.title for post in posts]
    elif filter_by == 'tag':
        tags = Tag.query.filter(Tag.tag.ilike(f'%{search}%')).all()
        suggestions = [tag.tag for tag in tags]
    else:
        suggestions = []

    return jsonify(suggestions)

# Route to display the user's posts
@main.route('/my_posts')
@login_required
def my_posts():
    """
    Route to display the user's posts.
    """
    page = request.args.get('page', 1, type=int)
    order = request.args.get('order', 'desc')
    heading = "My Posts"
    
    my_posts_query = Posts.query.filter_by(author_id=current_user.id, is_draft=False).order_by(
        Posts.date_posted.asc() if order == 'asc' else Posts.date_posted.desc()
    )
    
    pagination = my_posts_query.paginate(page=page, per_page=10, error_out=False)
    my_posts = pagination.items
    
    return render_template("main/my_posts.html", posts=my_posts, pagination=pagination, heading=heading, origin='my_posts')

# Route to view a specific post
@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def view_post(post_id):
    """
    Route to view a specific post.
    """
    post = Posts.query.get_or_404(post_id)
    origin = request.args.get('origin', 'posts')  # Default to 'posts' if not provided

    author = User.query.get_or_404(post.author_id)
    replies = Reply.query.filter_by(post_id=post_id).order_by(Reply.timestamp.asc()).all()
    form = ReplyForm()

    if form.validate_on_submit():
        reply = Reply(
            post_id=post_id,
            author_id=current_user.id,
            answer=form.answer.data,
            answered_accepted=False,
            deleted=False
        )
        db.session.add(reply)
        db.session.commit()
        flash('Your reply has been added.', 'success')
        return redirect(url_for('main.view_post', post_id=post_id, origin=origin))

    return render_template('main/view_post.html', post=post, author=author, replies=replies, form=form, origin=origin)

# API endpoint to toggle the acceptance of an answer
@main.route('/post/toggle_answer/<int:reply_id>', methods=['POST'])
@login_required
def toggle_answer(reply_id):
    """
    API endpoint to toggle the acceptance of an answer.
    """
    reply = Reply.query.get_or_404(reply_id)
    post = Posts.query.get_or_404(reply.post_id)

    if post.author_id != current_user.id:
        return jsonify({'success': False}), 403

    action = request.json.get('action')
    if action == 'accept':
        reply.answered_accepted = True
    elif action == 'reject':
        reply.answered_accepted = False

    db.session.commit()
    return jsonify({'success': True})

# API endpoint to edit a reply
@main.route('/post/edit_reply/<int:reply_id>', methods=['POST'])
@login_required
def edit_reply(reply_id):
    """
    API endpoint to edit a reply.
    """
    reply = Reply.query.get_or_404(reply_id)

    if reply.author_id != current_user.id or reply.answered_accepted:
        return jsonify({'success': False}), 403

    new_answer = request.json.get('answer')
    reply.answer = new_answer
    db.session.commit()
    return jsonify({'success': True})

# Route to edit a specific post
@main.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    """
    Route to edit a specific post.
    """
    post = Posts.query.get_or_404(post_id)

    if post.author_id != current_user.id:
        flash('You are not authorized to edit this post.', 'danger')
        return redirect(url_for('main.view_post', post_id=post_id))

    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        tag = Tag.query.filter_by(tag=form.tag.data).first()
        if tag is None:
            tag = Tag(tag=form.tag.data)
            db.session.add(tag)
            db.session.commit()
        post.tag_id = tag.id
        post.is_draft = False  # Remove draft status when editing a draft post
        db.session.commit()
        flash('Your post has been updated and published!', 'success')
        return redirect(url_for('main.view_post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.tag.data = post.tag.tag if post.tag else ''

    return render_template('main/edit_post.html', title='Edit Post', form=form, post=post)

# Route to display all posts
@main.route("/posts", methods=["GET", "POST"])
def posts():
    """
    Route to display all posts.
    """
    page = request.args.get('page', 1, type=int)
    order = request.args.get('order', 'desc')
    heading = "All Posts"
    
    all_posts_query = Posts.query.filter_by(is_draft=False).order_by(
        Posts.date_posted.asc() if order == 'asc' else Posts.date_posted.desc()
    )
    
    pagination = all_posts_query.paginate(page=page, per_page=10, error_out=False)
    all_posts = pagination.items
    

app/templates/includes/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CSSE DevConnect{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

<!-- slider stylesheet -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<!-- bootstrap core css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
<!-- font awesome style -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">


<!-- Custom styles for this template -->

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">

</head>
<body>
    {% include "includes/nav.html" %}

       
            {% block content %}{% endblock %}
        



  <!-- footer section -->
  <footer class="footer_section" style="position: static; height: 100px;">
    <div class="container">
      <p>
        &copy; <span id="displayDateYear"></span> All Rights Reserved By CSSE DevConnect.
      </p>
    </div>
  </footer>
  <!-- footer section -->



{% block scripts %}
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <script src="{{ url_for('static', filename='js/custom.js') }}"></script>

{% endblock %}

</body>
</html>

app/templates/includes/nav.html
<!DOCTYPE html>
<html lang="en">
<div class="hero_area">
    <!-- header section starts -->
    <header class="header_section">
        <div class="header_top">
            <div class="container-fluid">
                <div class="contact_nav">
                    <div class="row" style="width: 100%;">
                        <div class="col-md-2 text-left" style="font-size:28px">
                            <a href="{{ url_for('main.index') }}">
                                <span style="color: lightblue; font-size: 24px; font-weight: bold;">DevConnect</span>
                            </a>
                        </div>
                        <div class="col-md-3" style="margin-left: -75px; padding-top: 7px;">
                            <ul class="nav float-left" style="font-size: 18px; margin-top: -7px;">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.add_post') }}"> Ask Question </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.about') }}"> About Us</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-5" style="margin-top: -7px;">
                            <form class="d-flex ms-auto" method="GET" action="{{ url_for('main.search') }}">
                                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.args.get('q', '') }}">
                                <button class="btn btn-success" type="submit">Search</button>
                            </form>
                        </div>
                        <div class="col-md-2" style="margin-left: 50px; padding-top: -2px; margin-top: 7px">
                            {% if 'logged_in' in session and session['logged_in'] %}
                                <!-- User is logged in, show Profile and Logout -->
                                <span class="me-2" style="color: white;">{{ session['user_name'] }}</span>
                                
                            {% else %}
                                <!-- User is not logged in, show Login and Sign Up -->
                                <a href="{{ url_for('auth.login') }}" class="btn f-left btn-outline-light me-2">Login</a>
                                <a href="{{ url_for('auth.register') }}" class="btn btn-success">Sign Up</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header_bottom">
            <div class="container-fluid"></div>
        </div>
    </header>
</div>

<!-- Ensure Bootstrap's JavaScript is included -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>

app/templates/includes/sidebar.html
<!DOCTYPE html>
<html lang="en">

<!-- File: templates/sidebar.html -->

<div class="col-md-3 mylist mybd" >
    <!-- Dashboard Header -->
    <!-- <h4 class="pt-2">My Dashboard</h4> -->
    
    <!-- Bootstrap List Group for better styling -->
    <div class="card-header">
        <h5     >Question</h5>
    </div>
    <div class="list-group mb-3">
        <!-- Always visible links -->
        <a href="{{ url_for('main.add_post') }}" class="list-group-item list-group-item-action">
            <i class="fa fa-question-circle"></i> Ask Question
        </a>
        <a href="{{ url_for('main.posts') }}" class="list-group-item list-group-item-action">
            <i class="fa fa-list"></i> All Posts
        </a>
        <a href="{{ url_for('main.tags') }}" class="list-group-item list-group-item-action">
            <i class="fa fa-tags"></i> Tags
        </a>
        <a href="{{ url_for('main.career') }}" class="list-group-item list-group-item-action">
            <i class="fa fa-briefcase"></i> Career Preparation
        </a>
        <a href="{{ url_for('main.uni_preparation') }}" class="list-group-item list-group-item-action">
            <i class="fa fa-graduation-cap"></i> Unit Preparation
        </a>
    </div>

    <!-- Links visible only to authenticated users -->
    {% if session.logged_in %}
        <div class="card">
            <div class="card-header">
                <h5>My Content</h5>
            </div>
            <div class="list-group list-group-flush">
                <a href="{{ url_for('main.my_posts') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-user"></i> My Posts
                </a>
                <a href="{{ url_for('main.my_favorites') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-star"></i> Favorite Posts
                </a>
                <a href="{{ url_for('main.my_answers') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-reply"></i> My Answers
                </a>
                <a href="{{ url_for('main.drafts') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-pencil"></i> My Draft Posts
                </a>
            </div>    
        </div>
        <br>
        <div class="card">
            <div class="card-header">
                <h5>My Profile</h5>
            </div>
            <div class="list-group list-group-flush">
                
                <a href="{{ url_for('auth.profile') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-user"></i>Profile
                </a>
                <a href="{{ url_for('auth.logout') }}" class="list-group-item list-group-item-action">
                    <i class="fa fa-sign-out"></i> Logout
                </a>
            </div>    
        </div>
    {% endif %}
</div>

<!-- Make sure to include Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">